# Generated by Django 4.2.7 on 2025-12-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='About Me', max_length=200)),
                ('introduction', models.TextField()),
                ('show_education', models.BooleanField(default=True)),
                ('interests_title', models.CharField(default='Interests & Passion', max_length=200)),
                ('interests_subtitle', models.CharField(default='What drives me', max_length=200)),
                ('values_title', models.CharField(default='Core Values', max_length=200)),
                ('values_subtitle', models.CharField(default='Principles I live by', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
                'db_table': 'about_page',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Get In Touch', max_length=200)),
                ('page_subtitle', models.TextField(default="Have a project in mind or want to collaborate? I'd love to hear from you!")),
                ('connect_title', models.CharField(default="Let's Connect", max_length=200)),
                ('connect_description', models.TextField()),
                ('cta_title', models.CharField(default='Ready to Start a Project?', max_length=200)),
                ('cta_description', models.TextField(default="Let's work together to bring your ideas to life.")),
                ('cta_button_text', models.CharField(default='View My Work', max_length=50)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_location', models.BooleanField(default=True)),
                ('location_text', models.CharField(default='India', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
                'db_table': 'contact_page',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(default='accent-primary', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'core_values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'education',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Your Name', max_length=200)),
                ('hero_subtitle', models.TextField(default='MCA Student | Data Scientist')),
                ('hero_description', models.TextField()),
                ('show_stats', models.BooleanField(default=True)),
                ('custom_stat_label', models.CharField(default='Tech Stack', max_length=50)),
                ('custom_stat_value', models.CharField(default='5+', max_length=20)),
                ('cta_title', models.CharField(default="Let's Work Together", max_length=200)),
                ('cta_description', models.TextField(default="Have a project in mind? Let's create something amazing together.")),
                ('cta_button_text', models.CharField(default='Get In Touch', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
                'db_table': 'home_page',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(default='accent-primary', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'interests',
                'ordering': ['order'],
            },
        ),
    ]
