# Generated by Django 4.2.7 on 2025-12-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_aboutpage_contactpage_corevalue_education_homepage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this submission')),
            ],
            options={
                'db_table': 'contact_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
