# Generated by Django 4.2.7 on 2025-12-29 12:27

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def migrate_skill_categories(apps, schema_editor):
    Skill = apps.get_model('public', 'Skill')
    SkillCategory = apps.get_model('public', 'SkillCategory')
    category_cache = {}

    for skill in Skill.objects.order_by('pk'):
        category_name = (skill.category or '').strip()
        if not category_name:
            continue

        slug_base = slugify(category_name) or category_name.lower()
        category = category_cache.get(slug_base)

        if not category:
            slug_candidate = slug_base
            counter = 1
            while SkillCategory.objects.filter(slug=slug_candidate).exists():
                slug_candidate = f"{slug_base}-{counter}"
                counter += 1

            category = SkillCategory.objects.create(name=category_name, slug=slug_candidate)
            category_cache[slug_base] = category

        skill.category = str(category.id)
        skill.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'skill_categories',
                'ordering': ['-order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(migrate_skill_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='public.skillcategory'),
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-proficiency']},
        ),
    ]
