# Generated by Django 4.2.7 on 2025-12-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_skillcategory_alter_skill_options_blog_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_cta_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_hero_description',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_hero_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_hero_title',
            field=models.BooleanField(default=True),
        ),
    ]
