# Generated by Django 4.2.7 on 2025-12-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_homepage_show_cta_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='show_interests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='show_introduction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='show_page_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='show_stats_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='show_values',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_connect_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_contact_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_contact_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_cta_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_page_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_page_title',
            field=models.BooleanField(default=True),
        ),
    ]
