# Generated by Django 4.2.7 on 2026-01-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_aboutpage_show_interests_aboutpage_show_introduction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
        migrations.DeleteModel(
            name='CoreValue',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
